### ISSUE TITLE
Add module-info.java to all our JARs

### ISSUE THREAD

**Issue by manorrock** [piranhacloud/piranha#1022]

**Comment by Thihup** [comment]
Shrinkwrap has a lot of split packages :disappointed:

**Comment by manorrock** [comment]
If needs be we could create a Maven module that just pulls all that into one Java module

**Comment by Thihup** [comment]
Sounds good. I'll see what I can do

**Comment by Thihup** [comment]
As Piranha Micro is a shaded jar it makes the things harder because at compile time it only exports the _cloud.piranha.micro_, but the final artifact includes the other classes

**Comment by manorrock** [comment]
@arjantijms Any suggestions?
