### ISSUE TITLE
Change URL of Piranha Micro 20.8.0

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#1037]
It's pointing to the -all.jar (https://repo1.maven.org/maven2/cloud/piranha/piranha-micro/20.8.0/piranha-micro-20.8.0-all.jar) artifact, which does not exist anymore.
Change to the main jar (https://repo1.maven.org/maven2/cloud/piranha/piranha-micro/20.8.0/piranha-micro-20.8.0.jar)

**Comment by manorrock** [comment]
Good catch! Fixed
