### ISSUE TITLE
Change over to use Java 15

### ISSUE THREAD

**Issue by manorrock** [piranhacloud/piranha#1070]

**Comment by Thihup** [comment]
JaCoCo is not working with JDK 15 yet

**Comment by manorrock** [comment]
OK noted, we might have to setup the pipeline to run Java 14 and Java 15 for a while then ;) Note I filed this issue as a reminder to me to change over from using Zulu to AdoptOpenJDK when the time comes to upgrade to Java 15.

**Comment by Thihup** [comment]
Looks like JaCoCo released a new version with support to JDK 15: https://github.com/jacoco/jacoco/releases/tag/v0.8.6

**Comment by manorrock** [comment]
Please ignore CodeQL for the time being.
