### ISSUE TITLE
Document creating a custom Piranha Server using jlink

### ISSUE THREAD

**Issue by manorrock** [piranhacloud/piranha#1105]

**Comment by Thihup** [comment]
Probably it will be needed to use the [Moditect](https://github.com/moditect/moditect) to include the module-info in the third-party jars because jlink doesn't support automatic module name.

**Comment by manorrock** [comment]
Can that be done as part of the example or would it impact our build?

**Comment by Thihup** [comment]
I guess it would impact our build. I need to try running the JLink again to recall exactly which problems I've found.

**Comment by manorrock** [comment]
I will be blogging about this example once I get the actual Servlet doing something, but the JLink portion for it is at https://github.com/manorrock/sphynx-hue-lct06/blob/main/jlink/pom.xml 

It uses Piranha Nano + Default HTTP server + Servlet
