### ISSUE TITLE
Configure SonarCloud to properly scan tests and main files

### ISSUE THREAD

**Issue by agigleux** [piranhacloud/piranha#1244]
Hello,

I'm from [SonarSource](https://www.sonarsource.com/), the company making SonarCloud.io

While looking at the issues raised by SonarCloud on your code, I realized there is probably a configuration problem to get a clean analysis.
The expectation is that the test files are analyzed differently from the main files and thanks to that, security issues (vulnerabilities, hotspots) are raised only on main files.

I believe the source code of Piranha is not organized in the Maven classical way with a src/main/java, src/test/java structure.
Because of that some files are considered as "main" whereas they are "test" files such as [here](https://sonarcloud.io/project/issues?id=piranhacloud_piranha&resolutions=FALSE-POSITIVE&rules=javasecurity%3AS5131).

I would like to advise you to configure your pom.xml file by adding these [2 properties](https://sonarcloud.io/documentation/analysis/analysis-parameters/) to say where are your main and test files in your various modules:
* _sonar.sources_: comma-separated paths to directories containing main source files.
* _sonar.tests_: comma-separated paths to directories containing test source files.

Regards
Alex

**Comment by manorrock** [comment]
Hi Alex,

Thank you for having a look at this. Note that we do have src/main/java for code and src/test/java for tests. Note however that as we are implementing a container we have code that produces deployable units which validates functionality of said container and as such are to be found in the src/main/java directory as they are part of the deployable unit. Then we have tests that assert the proper behavior. Hence why you are seeing the word "Test" as part of the code.
