### ISSUE TITLE
Jakarta namespace change

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#1250]
We have some options to do with respect to the package change (from javax to Jakarta).

The results could be
1. Keep the code as javax and transform the result, having two variants  (like TomEE)
2. Keep the javax code in other branch and the baseline be the jakarta (like Tomcat)
3. Have only a Javax variant with dynamic transformation at runtime from Jakarta to Javax (like Payara)
3. Have only a Jakarta variant with dynamic transformation at runtime from Javax to Jakarta (I don't know any implementations doing that yet).

Depending on the choice we can pass both Servlet 4 and Servlet 5 with the same source code.

**Comment by manorrock** [comment]
I would prefer 3 or 4, where I am leaning towards 3 initially and 4 eventually.

**Comment by manorrock** [comment]
Feel free to create a jakartaee9 branch to experiment with option 3

**Comment by Thihup** [comment]
Unfortunately, I cannot create a pull request to a non-existent branch. Would you mind creating the branch, please?

**Comment by manorrock** [comment]
Done!

**Comment by Thihup** [comment]
We will need to define where to transform the classes.

We can 
 1. Redefine at the classloader, modify the bytes before calling the _Classloader.defineClass_
 2. Redefine all the classes before starting the application
 3. Use some java-agent to transform the classes (?)

About the transformation, the Eclipse Transformer uses java.io.File as API, so while it's OK to do with Piranha Server, Piranha Micro might suffer from this.

There are two other projects that maybe help us: [Wildfly Batovia](https://github.com/wildfly-extras/batavia) and [Payara Transformer](https://github.com/payara/transformer)

**Comment by manorrock** [comment]
We have the Resource API that might be of use here.

**Comment by Thihup** [comment]
I'm struggling to get something to work mainly because all uses of the Eclipse Transformer relies on using native file. One approach I have tried was using the [Jimfs](https://github.com/google/jimfs) to simulate a java.nio.file.Filesystem in memory. However, as the tools use the java.io.File, it was pretty much useless.

Sure we can create a temporary file, copy the bytes, call the transformer and read the bytes out. Unfortunately, this creates a lot of overhead.

Maybe you can give a try and have another perspective of the issue. What do you think?

**Comment by arjantijms** [comment]
What about a PR to the upstream Eclipse project to let it operate on byte arrays as well?

**Comment by Thihup** [comment]
I took a better look at the Eclipse Transformer source. Using the class _Transfomer_ it only works with java.io.File indeed.
However, all implementation of replacing uses

**Comment by arjantijms** [comment]
> Using the class Transfomer it only works with java.io.File indeed.

Indeed, but as soon as `File` is read and passed on, you could trace that and provide alternative method and/or arguments using a byte array.

>  all implementation of replacing uses the InputBufferImpl, which is basically a wrapper over byte array.

That should make it even easier. Almost always at some point a File is read and a byte buffer (or variant as you discovered) is used. The higher-up in the code that happens, the easier it should be.

**Comment by Thihup** [comment]
I've got something working with #1293.
It's able to deploy the Servlet 5.0 wars and pass a bunch of tests.
However, it still needs some fixes.
 - Transform the web.xml / web-fragment.xml (one web.xml declares `<exception-type>jakarta.servlet.ServletException</exception-type>`
 - Transform some String constants (like jakarta.servlet.error.exception to javax.servlet.error.exception)
 - Getting a resource via URL is not being transformed (`new URL().openStream().getInputStream()`)

**Comment by manorrock** [comment]
If there is a real ask then we can continue the exploration of the transformer. For now I think we should close this. Thoughts?

**Comment by Thihup** [comment]
I agree.
