### ISSUE TITLE
Update to latest Jakarta Expression Language release

### ISSUE THREAD

**Issue by manorrock** [piranhacloud/piranha#1345]
Blocked on eclipse-ee4j/el-ri#147

**Comment by arjantijms** [comment]
I staged a 4.0.1 with the new automatic module name here: https://jakarta.oss.sonatype.org/content/repositories/staging/org/glassfish/jakarta.el/4.0.1/

Please give it a go first to see if it works.

**Comment by Thihup** [comment]
It worked!

I don't know if there's any problem adding the staging repo to the root pom.xml. Maybe we can wait until the official release.
Otherwise, I can send a PR adding the staging repo too, and later we can remove it.

```xml
    <repositories>
        <repository>
            <id>staging</id>
            <url>https://jakarta.oss.sonatype.org/content/repositories/staging/</url>
        </repository>
    </repositories>
```

**Comment by manorrock** [comment]
Lets wait until it is available ;)

**Comment by arjantijms** [comment]
https://repo1.maven.org/maven2/org/glassfish/jakarta.el/4.0.1

**Comment by manorrock** [comment]
@arjantijms @Thihup Great work on the quick turn around!

**Comment by Thihup** [comment]
@manorrock Thanks :)
