### ISSUE TITLE
Validate HttpWebApplicationServer.processCookies against Servlet TCK

### ISSUE THREAD

**Issue by manorrock** [piranhacloud/piranha#1362]

**Comment by Thihup** [comment]
The cookie parsing needs to be reworked to parse both version 0 (Netscape format) and version 1 (RFC 2109).
Parsing the RFC 2109 cookie is a little tricky, though.

**Comment by manorrock** [comment]
Indeed tricky, but not impossible, right?

**Comment by Thihup** [comment]
Exactly ;)
