### ISSUE TITLE
Migrate ServiceContainerInitializers to Servlet 5

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#1369]
The Piranha Upload modules isn't been loaded in the new namespace because it relies on the ServiceLoader pattern using the file in the META-INF/services, not via module-info.
However, the cause is that the upload module is a shaded module, so its module-info doesn't get to the jar and it is loaded as an automatic module.
The quick fix is to move the old service loader file to the new namespace (javax.servlet.ServletContainerInitializer to jakarta.servlet.ServletContainerInitializer) but in the future, we need to see if it is necessary shading this module. If so, we may use the moditect plugin to generate it.

**Comment by manorrock** [comment]
The shading is necessary as we do not want to conflict if the customer shipped Apache FileUpload themselves. We'll need to figure out how to add the proper module-info. Feel free to capture this in a separate issue. Thanks!
