### ISSUE TITLE
Migrate from Jasper to WaSP

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#1372]
The implementation of the Jakarta Pages was split from the _jsp-api_ with the new name "WaSP".

@arjantijms Is there any plan to release an official release of the WaSP soon?
Looks like the https://github.com/eclipse-ee4j/jsp-api/commit/6acb1f0d45f6b472687a9237f36855532442bc23 didn't get to the Jasper 3.0.0 release.

**Comment by arjantijms** [comment]
Yes, the plan is to release soon. See https://projects.eclipse.org/projects/ee4j.wasp/releases/3.0.0

If you want, can you redo that commit? I figured I included everything, but seemingly something slipped through the cracks then.

**Comment by Thihup** [comment]
I mean, the WaSP 3.0.0 contains the commit, but not the Jasper 3.0.0 (https://mvnrepository.com/artifact/org.glassfish.web/jakarta.servlet.jsp/3.0.0).

So as the new code is in the WaSP repo and it contains the fix, I guess we just need to wait :)

**Comment by arjantijms** [comment]
Ah, thanks for the clarification.

**Comment by manorrock** [comment]
Once it is released rename the integration module pages/jasper to pages/wasp and put in a relocation POM. Then once that is all in place file a separate issue to remove the relocation POM in the next cycle
