### ISSUE TITLE
Blog entry for the modular feature

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#1414]
I'm planning to create a simple example of creating a Servlet to displaying the module and that is possible to use the module-info to provide service implementations (in the case I'm thinking of using the ServletContainerInitializer).

Is there something special you would like to see in this post, like trying out another feature or using other libraries?

**Comment by manorrock** [comment]
All up to you. Note we still need to get the styling for the blog. @arjantijms do you have any suggestions here?

**Comment by Thihup** [comment]
I think I've got something ready. What should I do now?
The blog is in the gh-pages branch or is it located somewhere else?

**Comment by manorrock** [comment]
@arjantijms Should we just use the same styling as our documentation for now and just commit it to GitHub pages?

**Comment by arjantijms** [comment]
@manorrock Could do, although eventually would be nice if we could use the style from the homepage (https://piranha.cloud) a bit more for consistent and recognisable styling.

**Comment by manorrock** [comment]
Thiago, please go ahead and use regular GItHub pages markdown and put it in the blog/2021/YYYYMMDD_your_article_name (note do not use an extension here).

**Comment by manorrock** [comment]
Let's set the date to this coming Tuesday or Thursday for publishing, whichever one you think you can be ready for.

**Comment by Thihup** [comment]
Sure. Just one quick question: should the article be written in Markdown or in plain HTML?
