### ISSUE TITLE
Fix JarResource to properly close the JarFile used in getAllLocations

### ISSUE THREAD

**Issue by manorrock** [piranhacloud/piranha#1418]
As reported by https://sonarcloud.io/project/issues?id=piranhacloud_piranha&open=AXbaiaDOFpO56REPgXdi&resolved=false&sinceLeakPeriod=true&types=BUG

**Comment by Thihup** [comment]
As we cannot use the JarFile#stream and try-with-resources, probably the best way to fix is to copy all the file names to a temporary list and use it as the return of the getAllLocations
