### ISSUE TITLE
Create a custom implementation of Weld SPI to avoid Illegal access error

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#1428]
Running Weld with JDK 15 gives us the following warning:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jboss.weld.util.bytecode.ClassFileUtils$1 (shrinkwrap://weld-core-impl-4.0.0.Final.jar/org/jboss/weld/util/bytecode/ClassFileUtils$1.class) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of org.jboss.weld.util.bytecode.ClassFileUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
With the JDK 16, however, this fails because they have changed the default behavior from `--illegal-access=permit` to `--illegal-access=deny` and have deprecated the `--illegal-access` flag.

In the Javadoc [1] of the `org.jboss.weld.util.bytecode.ClassFileUtils` says:
> [...] This mostly concerns Weld SE, EE integrators should already go through new SPI hence avoiding this problem.

However, the Javadoc doesn't specify which SPI should be used. Check if we can find which SPI they are referring to and if we can create our own implementation to avoid the illegal access error.

[1] https://javadoc.io/doc/org.jboss.weld/weld-core-impl/latest/org/jboss/weld/util/bytecode/ClassFileUtils.html

**Comment by Thihup** [comment]
Related issue: https://issues.redhat.com/browse/WELD-2581

**Comment by Thihup** [comment]
There is a PR to address it on the Weld side.

https://github.com/weld/core/pull/2240

We need to test to see if we still need to open all modules to Weld when running the applications in the JPMS layers.

**Comment by manorrock** [comment]
So if we would run it with --illegal-access=permit it would work?

**Comment by Thihup** [comment]
Yes, but they have deprecated the --illegal-access in JDK 16 too. So we can use it for granted for JDK 16 but not for JDK 17. Probably until there will be fixes available in the corresponding projects ;)

**Comment by manorrock** [comment]
OK can you please add the flag to our pipeline using a separate issue and linking here. We'll keep this one open for tracking Weld

**Comment by arjantijms** [comment]
> However, the Javadoc doesn't specify which SPI should be used. Check if we can find which SPI they are referring to and if we can create our own implementation to avoid the illegal access error.

I was wondering about the same. The current convenience API we use if for pure Servlet containers. It does have knowledge about those containers, though we seem to be able to integrate for now without being known. Potentially the specific integration is to be able to inject transparently in Servlets and such, but I need to double check.

Also need to check what exactly the difference is between the EE integrator targeted SPI and the convenience API. The integration code in GF or instance is quite big, and eventually it does most of the same things.

**Comment by arjantijms** [comment]
I also asked a question in the linked JIRA issue what the new SPI is.

**Comment by Thihup** [comment]
In this case, looks like they are referring to the ProxyServices SPI [1]. I have tried to use it, but I have hit the same problem that is defining a class only using standard APIs.
Today we have two standard ways of defining the classes: 
- Using a Classloader.defineClass (via subclassing the Classloader)
- Using MethodHandles.defineClass

However, I couldn't figure out the way of defining classes in arbitrary packages using MethodHandles, the same issue the PR tries to solve.

[1] https://docs.jboss.org/weld/javadoc/3.0/weld-spi/org/jboss/weld/serialization/spi/ProxyServices.html

**Comment by Thihup** [comment]
They have fixed in the master using Multi Release jars. The next version will include the fix.
We may implement it in the future if needed, but for now, we need to add support for multi-release jars (https://github.com/piranhacloud/piranha/issues/1543)
