### ISSUE TITLE
Update OpenWebBeans to Servlet 5 / Jakarta EE 9

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#1480]
The OpenWebBeans already provides the Jakarta versions of their artifacts using the Jakarta classifier.
However, each of the artifacts still requires the artifact without a classifier.
I have opened an issue to see if they can fix up their POMs. If not, we can still update on our side, by excluding all the normal dependencies and requiring the dependencies with the Jakarta classifier.

https://issues.apache.org/jira/browse/OWB-1368

**Comment by manorrock** [comment]
I would prefer waiting to the ones without classifier
