### ISSUE TITLE
AJAX functionality not working

### ISSUE THREAD

**Issue by adam-waldenberg** [piranhacloud/piranha#1498]
I have been playing around with MyFaces and Mojarra in conjunction with Piranha Micro (and embedded). Most JSF functionality seems to work using the provided artifacts - with the exception of AJAX calls. I have tried vanilla `<f:ajax>` and PrimeFaces `update` attributes with no success. The result is the same with both MyFaces and Mojarra.

I've kept it simple and I'm using the `DefaultHttpServer` implementation.

Am I I missing something ? Is it supposed to work ? If so - tips are appreciated. As it is, I can see the request is actually sent - but beyond that it doesn't seem to be able to associate or get any response  back.

/ Adam

**Comment by manorrock** [comment]
@adam-waldenberg Do you have a sample we can try?

**Comment by adam-waldenberg** [comment]
Here are the relevant parts.... `index.xhtml` is a bit of a mess - been playing around a bit with the search expressions - but whatever I do I can't seem to get it to work properly.

```
<?xml version='1.0' encoding='UTF-8' ?>  
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:o="http://omnifaces.org/ui">
	<h:head>
		<title>User Form</title>
	</h:head>
	<h:body>
		<h:form>
			<h:outputLabel for="username">User Name</h:outputLabel>
			<h:inputText id="username" value="#{welcomeController.name}" required="true" requiredMessage="User Name is required" /><br/>
			<p:commandButton value="Submit PrimeFaces" action="#{welcomeController.onPress}" update="@(.shit) @form" />
			<h:commandButton value="Normal JSF" action="#{welcomeController.onPress}">
				<f:ajax execute="@form" render="@form momo" />
			</h:commandButton>
			The name is #{welcomeController.name}
			<br/>
		</h:form>
		<h:panelGroup id="" styleClass="shit">
		The name is #{welcomeController.name}
		</h:panelGroup>
	</h:body>
</html>
```

```
@Data
@Named("welcomeController")
@ViewScoped
public class WelcomeController implements Serializable {
	@Inject
	private transient Logger logger;

	private String name;

	public void onPress() {
		logger.info("shitpickle pressed the button");
	}
}
```

```
@ApplicationScoped
public class LoggerProducer {
	@Produces
	public Logger produceLogger(InjectionPoint point) {
		return Logger.getLogger(point.getMember().getDeclaringClass().getName());
	}
}
```

```
@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class Main {
	public static void main(String[] args) throws InterruptedException {
		System.getProperties().put("java.naming.factory.initial",
			"cloud.piranha.naming.impl.DefaultInitialContextFactory");

		HttpWebApplicationServer server = new HttpWebApplicationServer();
		HttpServer httpServer = new DefaultHttpServer(8180, server, false);
		DefaultWebApplication application = new DefaultWebApplication();

		server.addWebApplication(application);
		application.addResource(new DirectoryResource("src/main/webapp"));
		application.addResource(new AliasedDirectoryResource(new File("target/classes"), "/WEB-INF/classes"));

		application.addInitializer(WeldInitializer.class.getName());
		application.addInitializer(MyFacesInitializer.class.getName());

		server.initialize();
		server.start();

		httpServer.start();
		Thread.sleep(50000); // Sleep so we can manually send a request and test...
		httpServer.stop();

		server.stop();
	}```

**Comment by adam-waldenberg** [comment]
Sidenote: I also tried running it without PrimeFaces and OmniFaces. Same result.

**Comment by adam-waldenberg** [comment]
@manorrock Here's also a tarball with an example project:

https://drive.google.com/file/d/1qrrV1A6uy2wAjfin0QxRl92OarxbUqfN/view?usp=sharing

**Comment by manorrock** [comment]
It looks like it is not accessible?

**Comment by adam-waldenberg** [comment]
[janus-java.tar.gz](https://github.com/piranhacloud/piranha/files/5977942/janus-java.tar.gz)

Try this @manorrock

**Comment by manorrock** [comment]
@adam-waldenberg Are you OK if we use this as a test/example in our test bed?

**Comment by adam-waldenberg** [comment]
@manorrock go for it

**Comment by adam-waldenberg** [comment]
@manorrock I just realized - maybe it's related to AjaxBehaviorRenderer ? Is it perhaps not loaded ?

**Comment by adam-waldenberg** [comment]
@manorrock Adding a custom renderer kicks it into life -

![image](https://user-images.githubusercontent.com/1555683/107885249-71cb6800-6ef9-11eb-9948-b41983c1b64c.png)

```
public class CustomAjaxBehaviorRenderer extends ClientBehaviorRenderer {
	@Override
	public String getScript(ClientBehaviorContext behaviorContext, ClientBehavior behavior) {
		return "alert('Show an alert!')";
	}
}
```

and into faces-config.xml:
```
	<render-kit>
		<client-behavior-renderer>
			<client-behavior-renderer-type>jakarta.faces.behavior.Ajax</client-behavior-renderer-type>
			<client-behavior-renderer-class>org.unigrid.janus.CustomAjaxBehaviorRenderer</client-behavior-renderer-class>
		</client-behavior-renderer>
	</render-kit>
```

**Comment by adam-waldenberg** [comment]
So going back to the original renderer for the component I can see that the `jakarta.faces.ViewState` input is being updated - so that part is working correctly.

**Comment by manorrock** [comment]
Does that work as a workaround for now? Still trying to debug this one. We'll probably need to add some more feature to make debugging easier.

**Comment by Thihup** [comment]
I've found a bug:
During the parsing of the POST request, it checks if the content type is `application/x-www-form-urlencoded`, however, the browser is sending `application/x-www-form-urlencoded;charset=UTF-8` so it doesn't parse the parameters from the request.

**Comment by manorrock** [comment]
Interesting ... can you create a fix?

**Comment by Thihup** [comment]
With the fix #1527
![image](https://user-images.githubusercontent.com/13357965/109397614-522f3900-7916-11eb-97d1-0af5a977f01b.png)

**Comment by manorrock** [comment]
@Thihup Can you trigger the nightly workflow so @adam-waldenberg test the 21.3.0-SNAPSHOT version, so he can validate the fix from his end?

**Comment by adam-waldenberg** [comment]
Yep! Initial tests seem to suggest this fixes the issue!

**Comment by manorrock** [comment]
@adam-waldenberg Good to hear. Next release will be on the 13th so stay tuned!

**Comment by adam-waldenberg** [comment]
@manorrock Looking forward to it!
