### ISSUE TITLE
Simplify Javadocs

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#1500]
Starting with JDK 16, it is possible to avoid repeating the Javadoc of simple cases, like getters and setters. It should help with DRY.

https://stackoverflow.com/questions/10088311/javadoc-return-tag-comment-duplication-necessary/66220601#66220601

**Comment by manorrock** [comment]
Go for it! ;)

**Comment by Thihup** [comment]
Depends on #1487

**Comment by manorrock** [comment]
Closing this issue as the PRs filed by @jaferkhan have addressed this. Any other work that could be done will use separate issues where appropriate.
