### ISSUE TITLE
Add support for multi-releases Jar

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#1501]
Weld is going to release a fix to https://github.com/piranhacloud/piranha/issues/1428. However, as it wants to be compatible with JDK 8+, they will be using multi-releases Jar [1]

The JarFile class already supports it, so Piranha Server should be OK, but the other in-memory resources are not. 

[1] https://issues.redhat.com/browse/WELD-2581

**Comment by manorrock** [comment]
I would prefer separate Resource implementation that understand this. That way when used programmatically you determine the extent of how resources are resolved. Thoughts?

**Comment by Thihup** [comment]
Fair enough. I've thought about a resource wrapper that could return the correct version of some class. I'll give it a try soonish.
