### ISSUE TITLE
Add Thiago to the developers section of our POM

### ISSUE THREAD

**Issue by manorrock** [piranhacloud/piranha#1516]
@Thihup Congratulations after you issue a PR to add the relevant content I will add you as a GitHub contributor to the project which is equivalent to having direct committer access. You have demonstrated what it means to contribute to Open Source. A huge THANK YOU!

**Comment by manorrock** [comment]
@Thihup You are now fine to merge at your own leisure. Just make sure the build keeps passing ;)

**Comment by Thihup** [comment]
@manorrock Sure. Is there any problem to keep using the PR feature to have a feedback if the changes are OK?

**Comment by manorrock** [comment]
No problem whatsoever if you want feedback. But I suggest if you now want a review to ask me or @arjantijms using the reviewer feature as I won't be looking at every PR now ;)
