### ISSUE TITLE
Get the same HttpSession if available

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#1529]
Myfaces relies on the HttpSession to work. When it wants to set an attribute, it calls `request.getSession(true)`, but now we are creating a new session everytime this method is called. It should reuse the same session if available.

Related #1498

**Comment by manorrock** [comment]
Mmmm that should work. I admit it has been a while since I looked at that particular area of the code.

**Comment by Thihup** [comment]
I need to take a better look. I guess it is not working when a the JSESSIONID is invalid.

**Comment by Thihup** [comment]
Well, it is working. Yesterday when I looked it was returning a new session with the empty attributes, causing the request to fail, but probably it was some browser cache as now it is working 🤷🏼‍♂️
