### ISSUE TITLE
Use the Stream::toList method

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#1548]
Starting with JDK 16, there is the `Stream::toList`, where it returns an immutable list.
Check where is possible to replace the `collect(Collectors.toList())` and `collect(Collectors.toUnmodifiableList()` with `.toList()`

**Comment by manorrock** [comment]
Remember that the upcoming version will still require Java 15. This would be for the 21.4.0 release ;)

**Comment by Thihup** [comment]
Sure ;)

**Comment by manorrock** [comment]
Depends on #1487
