### ISSUE TITLE
Use pattern variables where possible

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#1563]
JDK 16 has support for pattern variables, where it allows to simplify instanceof and cast. More information: https://openjdk.java.net/jeps/394

Example:
```java
    if (previousRequest instanceof DefaultWebApplicationRequest) {
        DefaultWebApplicationRequest defaultRequest = (DefaultWebApplicationRequest) previousRequest;
        // ...
    }
```

```java
    if (previousRequest instanceof DefaultWebApplicationRequest defaultRequest) {
        // ...
    }
```

**Comment by manorrock** [comment]
@jaferkhan Just a note that until you reach committer status any issue you work on will be assigned to the reviewing commiter(s).
