### ISSUE TITLE
Replace JUL with Platform Logging API

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#1612]
In Java 9, they've added the Platform logging API [1]
Currently, we are using java.util.logging. I guess we are using it because this project started targeting JDK 8, where the System.Logger class was not available.
By default, it will use the JUL, but it allows us to create smaller images.

The changes would be trivial, but there are some differences:
|JUL| System.Logger|
|---|---|
|Level.SEVERE|Level.ERROR|
|Level.FINE|Level.DEBUG|
|Level.FINER|Level.TRACE|

The methods like `logger.info(...)` will change to `logger.log(INFO, ...)`

Using this API, we could easily swap to other implementations in the future if we needed.

The changes can be seen here: https://github.com/Thihup/piranha/commit/287433b201f8336200ee74e0ed97056f8b30b9d1

What do you think?

[1] https://openjdk.java.net/jeps/264
API: https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/System.Logger.html

**Comment by manorrock** [comment]
Go for it. Be aware that we should still ship java.util.logging for Micro and Server as you have to opt into an implementation. We just do not have a compile time dependency anymore.
