### ISSUE TITLE
Fix session TCK tests

### ISSUE THREAD

**Issue by manorrock** [piranhacloud/piranha#1670]
Fix the following TCK tests related to session functionality

1. ~~com/sun/ts/tests/servlet/pluggability/api/jakarta_servlet_http/sessioncookieconfig/URLClient.java#constructortest1~~
1. ~~com/sun/ts/tests/servlet/api/jakarta_servlet_http/sessioncookieconfig/URLClient.java#constructortest1~~
1. com/sun/ts/tests/servlet/api/jakarta_servlet_http/httpsessionx/URLClient.java#invalidateHttpSessionxTest
1. com/sun/ts/tests/servlet/api/jakarta_servlet_http/httpsessionx/URLClient.java#expireHttpSessionTest
1. com/sun/ts/tests/servlet/api/jakarta_servlet_http/httpsession/URLClient.java#expireHttpSessionTest

**Comment by Thihup** [comment]
Currently, we are not invalidating the expired sessions. This is the main cause of the failures.
So, we need some implementation that expires based on time. I don't think adding a new dependency just for this is worth it. However, implementing from scratch may be error-prone.
I was thinking of adding a class like this one: https://gist.github.com/pcan/16faf4e59942678377e0
But I don't know if the license is would allow it.

About libraries that we could use, I have two in mind: https://github.com/ben-manes/caffeine and Guava.

Thoughts @mnriem?

**Comment by mnriem** [comment]
@Thihup I have added a reapSessions method (see #1870) which hopefully should do the trick. See DefaultHttpSessionManager constructor to see how it gets triggered. I hope this will be enough. Now we "just" need to make sure it passes these TCK tests (corner cases are always tricky) ;)

**Comment by mnriem** [comment]
Note for our core APIs I am trying to now introduce any other dependencies unless we absolutely cannot do it any other way. This is to make sure the embedding scenario is as easy as it can get. Note that I would never recommend the usage of Guava anywhere as they have broken backwards compatibility frequently.

**Comment by Thihup** [comment]
Sure! I really didn't want to include Guava either, it was just another dependency I could think of.
I have never used the `ScheduledExecutorService::scheduleWithFixedDelay`, it seems powerful 😎
