### ISSUE TITLE
Change over to use Eclipse Jakarta Servlet dependency if possible

### ISSUE THREAD

**Issue by manorrock** [piranhacloud/piranha#1753]

**Comment by Thihup** [comment]
Is the plan to repackage it? For now, they don't include a module-info.class, only the Automatic-Module-Name.
We could use Moditect to add a module-info to it and release it as a Piranha dependency or try to get the module-info in the servlet-api repository.
Apart from that, I think we would even pass some tests.

**Comment by manorrock** [comment]
We probably should work with them to get a proper module-info added. @Thihup you willing to spear head that with them?

**Comment by Thihup** [comment]
FYI: https://github.com/eclipse-ee4j/servlet-api/issues/201

**Comment by mnriem** [comment]
We will wait to do this until Jakarta EE 10 which will include Jakarta Servlet 6. See #1793
