### ISSUE TITLE
Fix SonarCloud bug

### ISSUE THREAD

**Issue by manorrock** [piranhacloud/piranha#1784]
See https://sonarcloud.io/project/issues?id=piranhacloud_piranha&resolved=false&types=BUG

**Comment by Jeyabal-B** [comment]
I will work on this

**Comment by Jeyabal-B** [comment]
Fixed it, please check the PR once.
https://github.com/piranhacloud/piranha/pull/1785

**Comment by manorrock** [comment]
@Jeyabal-B  As this is your first contribution please acknowledge that you agree that your contributions will be owned by Manorrock.com and that Manorrock.com can use your contributions in any manner Manorrock.com so desires.

**Comment by Jeyabal-B** [comment]
Acknowledged.

**Comment by manorrock** [comment]
Thank you and congratulations your first PR just got merged!
