### ISSUE TITLE
Check which classes could be records

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#1800]
IntelliJ suggests that some of the classes that exist could be records. Converting some classes to records now can prepare the way for other kinds of pattern matching in the future.

One thing to notice is where is OK to expose the accessor to the field and where it is not OK.

```
AliasedNamedResource
ApacheMultiPart
DefaultAnnotationManager.DefaultAnnotationInfo
DefaultAsyncDispatcher
DefaultHttpServerAcceptorThread
DefaultHttpServerProcessingThread
DefaultInvocationFinder
DefaultModuleReader
DefaultNamingManager
DefaultSecurityPrincipal
DefaultUserTransaction
EmbeddedHttpServerProcessor
GrizzlyHttpServerRequest
GrizzlyHttpServerResponse
InMemoryIdentityStore.Credential
JdkHttpHandler
MicroInnerApplication
NanoHttpServerProcessor
UndertowHttpHandler
UndertowHttpResponse
WebXmlContextParam
WebXmlErrorPage
WebXmlLoginConfig
WebXmlMimeMapping
WebXmlServletMapping
```

**Comment by Thihup** [comment]
@manorrock What would be the policy for removing getters/setters from WebXml* classes? Would we need to mark them as deprecated for removal and remove them in the next version or could we just remove them? I'm assuming these are implementation classes.

Several WebXml* classes could be records, however, some of them don't initialize all the values in the constructor, requiring the setters.

**Comment by manorrock** [comment]
@Thihup Anything on the master branch can be changed without going through a deprecation process. As it is our bleeding edge. Once Java 17 comes out we will create a branch that will be our stable branch where we will only do bug fixes. Then once the next Java LTS comes out after the Java 17 branch will become the legacy branch for which we will do only security fixes and the next Java LTS becomes the stable branch. So in a nutshell go for it!
