### ISSUE TITLE
Create directory .mvn in the root of the project

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#1856]
Maven 4 allows going to a subproject and run `mvn verify` and it will include all the modules it requires for that module to build.
For instance, if we go to the `webapp/impl` folder and run `mvn verify` it will work just fine without requiring the `install` phase to be executed.

However, there is one request to this feature work correctly: That a ".mvn" folder exists in the top-level directory.
As Git doesn't allow to have empty folders, creating a dummy file like ".gitkeep" solve this issue.

Note that this doesn't change any Maven requirement, so it still works with Maven < 4

https://maarten.mulders.it/2020/11/whats-new-in-maven-4/

**Comment by mnriem** [comment]
If it does not impact/change any previous Maven behavior go for it!
