### ISSUE TITLE
Cache Maven dependencies of workflows

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#1876]
Setup Java now supports caching Maven dependencies using only one flag. This might improve some build time in the workflows.

https://github.com/actions/setup-java#caching-packages-dependencies
https://github.blog/changelog/2021-08-30-github-actions-setup-java-now-supports-dependency-caching/

**Comment by mnriem** [comment]
As the workflow has been split out in more than one workflow this will be closed as 'won't fix'
