### ISSUE TITLE
Rename master branch to current

### ISSUE THREAD

**Issue by mnriem** [piranhacloud/piranha#1885]
1. Create the current branch
2. Attribute missing commits to relevant users
3. Change default branch to current
4. Move any commits made in master branch into current

Note normally one would just rename the branch and be done, but because the 'manorrock' account was elevated to an organization and it owned a lot of commits the commit history graph is now incomplete. This procedure will make sure that all commits are properly attributed going forward.

**Comment by mnriem** [comment]
@Thihup I created the current branch and changed it to be the default. Please check it out to commit to going forward. I hope this is not too disruptive. Thanks!

**Comment by Thihup** [comment]
@mnriem OK! ;)
