### ISSUE TITLE
Copying zip file to running server does not deploy

### ISSUE THREAD

**Issue by folker-kuhn** [piranhacloud/piranha#1950]
When we start the Piranha Server and have a war file in the web apps folder, all is fine and Piranha starts it. Now it we have a running server and copy a war file, Piranha does nothing.

I think this is not what the user expects, and GlassFish and WildFly do monitor this folder and then do automatic deploy.

**Comment by Thihup** [comment]
Currently, Piranha Server doesn't support automatic deploy and undeploy of applications, so it is required to have them in the webapps.

**Comment by folker-kuhn** [comment]
@Thihup That's what I saw. Can you/we/someone add such support? It would be a good feature.

**Comment by mnriem** [comment]
@Thihup Would you be willing to take this on as an add-on web application? As part of a set of companion web applications that can be deployed on Piranha Server to extend its core functionality? Call it 'autodeployer' and make it listen to changes in the webapps directory.

**Comment by mnriem** [comment]
If you need a singleton to access the ServerPiranha instance please add it to ServerBootstrap and then get it from there.

**Comment by Thihup** [comment]
@mnriem Do you mean like `autodeployer.war` that when it is in the webapps folder it will listen to changes or something else?

**Comment by mnriem** [comment]
Yea that is what I mean.
