### ISSUE TITLE
Refactor core/jpms into core/api and core/impl

### ISSUE THREAD

**Issue by mnriem** [piranhacloud/piranha#2004]
Rough sketch

1. Move implementation to DefaultModuleLayerProcessor
2. Introduce an interface for ModuleLayerProcessor
3. Move API to core/api
4. Move implementations (DefaultXXX) to core/impl

@Thihup Can you have a look to see if this is possible?

**Comment by Thihup** [comment]
@mnriem It is totally possible, however, the tests are a little more difficult to move, because it uses Shrinkwrap, and it won't compile with a module-info due split packages 😞.
Maybe the DefaultModuleLayerProcessor could be a singleton, as it is stateless.

**Comment by mnriem** [comment]
Could the tests live in a separate module say in the test subtree, e.g. test/jpms? And is the rest then still possible?
