### ISSUE TITLE
Change over to use Eclipse Jakarta Servlet dependency 

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#2091]
Now that https://github.com/eclipse-ee4j/servlet-api/pull/442 is merged, we need to wait for a new release of the API in Maven Central, then we can switch to it.

Related: https://github.com/piranhacloud/piranha/issues/1753

**Comment by mnriem** [comment]
Not entirely sure if this is a 5.x release or not. If not we'll have to wait until EE 10 is out the door.

**Comment by mnriem** [comment]
Tracking as part of #2497
