### ISSUE TITLE
Create a Maven plugin for Piranha Micro to enable inner loop development

### ISSUE THREAD

**Issue by mnriem** [piranhacloud/piranha#2109]

**Comment by mnriem** [comment]
This plugin should:

1. Be able to be added to the build plugins without interfering with any other plugin
1. Support a piranha-micro:run goal which runs the web application in place
1. Support a piranha-micro:start goal which starts the application in a separate process
1. Support a piranha-micro:stop goal which stops the application that was started in a separate process

**Comment by mnriem** [comment]
@Thihup All the goals mentioned above should work. Please give it a try. It is currently set to run the Standard version. If you find anything let me know.

**Comment by Thihup** [comment]
@mnriem Awesome work! Good job! It is pretty amazing to be able to switch from Piranha Micro to Piranha Server and still have the same loop development.
Both 
```
mvn piranha-micro:stop package piranha-micro:run
```
```
mvn piranha-server:stop package piranha-server:run
```
Worked just fine.
