### ISSUE TITLE
Create start.cmd for starting Piranha Server on Windows

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#2119]
It is already specified in our code a couple of times, however, we don't have it yet.
Probably trying to build the project on Windows will fail with this error.

**Comment by mnriem** [comment]
If you are on Windows have a go at it. If .cmd proofs to be to much hassle I would be OK if we mandate PowerShell

**Comment by Thihup** [comment]
Currently, I'm not 😫 . I'll mark this issue as help wanted
