### ISSUE TITLE
Use CDS in start.sh

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#2148]
Probably if we include the script like specified in the manpage of Java in the start.sh, we could benefit from a faster startup in a loop environment.

Some testing would be required to see if there are some performance improvements.

https://docs.oracle.com/en/java/javase/17/docs/specs/man/java.html#creating-a-shared-archive-file-and-using-it-to-run-an-application

**Comment by mnriem** [comment]
Go for it!

**Comment by arjantijms** [comment]
Hi @Thihup just wondering, did you ever look at this?

Might be interesting too to base a blog article on.

**Comment by Thihup** [comment]
Hi @arjantijms!
I have done some tests a few months ago, but a new test would be appropriate and document the results.
Also, I want to have a look using the `-Xshareclasses` from OpenJ9 ([IBM Semeru](https://developer.ibm.com/languages/java/semeru-runtimes/downloads)), which is similar to CDS. Maybe creating a blog post about both would be awesome.

I'm very busy at the moment, but as soon as I get some free time I want to have a better look at this.
