### ISSUE TITLE
Allow setting a custom repository URL in Maven plugin

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#2161]
This way we can try out the SNAPSHOT version by changing the property to something like: `-Dpiranha.server.repository.url=file:///home/$USER/.m2/repository/`

**Comment by mnriem** [comment]
@Thihup if the version is not available from the remote repository it looks if the zip file happens to be in your local repository and then uses it.

**Comment by Thihup** [comment]
@mnriem That's right, I thought it broke because of the exception printed.
