### ISSUE TITLE
Add create-annotation-index goal to piranha-server/micro plugins

### ISSUE THREAD

**Issue by mnriem** [piranhacloud/piranha#2227]
To make bootstrap faster we should add a create-annotation-index goal to piranha-server/micro plugin that creates an index that a WebApplicationExtension can use.

1. Make sure the default annotation scanning is triggered at the right time
2. Make sure the default annotation scanning can be turned off / skipped.
3. Create the create-annotation-index goal for piranha-server plugin (by default run at pre-package)
4. Create the create-annotation-index goal for piranha-micro plugin (by default run at pre-package)
5. Add the AnnotationIndexWebAplicationExtension before the default annotation scanning which will use the index if it exists and then disable the default annotation scanning, or it will skip when the index is not found.

Note implementation wise do not include external dependencies. The current AnnotationScanExtension already knows how to do a deep annotation scan so we should mimic that behavior to do the scanning and then generate/store the index.

**Comment by mnriem** [comment]
@Thihup Is this something you would like to take on?

**Comment by Thihup** [comment]
Hi @mnriem. Unfortunately, right now I'm short of time to implement this feature 😞

**Comment by Thihup** [comment]
Implementation-wise, maybe we could basically just serialize some record class with all the information we need. https://inside.java/2021/03/12/simpler-serilization-with-records/

**Comment by mnriem** [comment]
@Thihup No worries. The project is not going anywhere. If you have time in the future and it is still open have a go at it. Otherwise pick another one ;)
