### ISSUE TITLE
Piranha doesn't support building in parallel 

### ISSUE THREAD

**Issue by arjantijms** [piranhacloud/piranha#2325]
Building Piranha in parallel using e.g.

```
mvn clean install -T10
```

results in the follow error aborting the build:

[ERROR] Failed to execute goal cloud.piranha.maven.plugins:piranha-server-maven-plugin:22.1.0-SNAPSHOT:start (pre-integration-test) on project piranha-test-server: java.nio.file.NoSuchFileException: /piranha/.m2/repository/cloud/piranha/server/piranha-server-standard/22.1.0-SNAPSHOT/piranha-server-standard-22.1.0-SNAPSHOT.zip -> [Help 1]

[ERROR] Failed to execute goal cloud.piranha.maven.plugins:piranha-server-maven-plugin:22.1.0-SNAPSHOT:start (pre-integration-test) on project piranha-test-mojarra: java.nio.file.NoSuchFileException: /piranha/.m2/repository/cloud/piranha/server/piranha-server-standard/22.1.0-SNAPSHOT/piranha-server-standard-22.1.0-SNAPSHOT.zip -> [Help 1]

**Comment by mnriem** [comment]
The build was not setup to be done in parallel. So I have changed this from a bug to an enhancement and also asking for help :)

**Comment by OndroMih** [comment]
It looks like the build isn't an issue, but running Piranha Micro multiple times in parallel is an issue, leading to reading of a JAR in an inconsistent state. This is described in this comment: https://github.com/piranhacloud/piranha/issues/1948#issuecomment-955201505. This then fails parallel executions of integration tests, where each of them starts its own Piranha Micro instance.

**Comment by OndroMih** [comment]
I investigated paralle builds and the reason for corrupted JARs is different - the JARs are being built in parallel to running the tests that need them. These builds need to be synchronized and Maven already does it but sometimes it can't figure out the dependencies correctly and needs some "hints".

I believe I've fixed this issue as well as some other timing issues with: #2584
