### ISSUE TITLE
Run build-ea workflow with latest EA JDK 

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#2530]
This will require using the https://github.com/oracle-actions/setup-java

**Comment by mnriem** [comment]
I am OK waiting for Adoptium EA releases. No hurry here ;)

**Comment by mnriem** [comment]
I am considering expiring the build-ea workflow and just have the build workflow target the latest released version and the latest LTS version and leave it at that. Thoughts?

**Comment by arjantijms** [comment]
Test early, test often? Would be good to, in this case, start testing with JDK 19.

**Comment by mnriem** [comment]
@Thihup If you can maintain this please let us know. If not, I will expire this workflow.

**Comment by Thihup** [comment]
@mnriem I think I can maintain this workflow ;)
The only issue is that Eclipse Temurin has a slow process to release the EA, so that's why I think we might have to use the oracle/setup-java, at least for the EA workflow
