### ISSUE TITLE
JSP used as a welcome page treated as static resource

### ISSUE THREAD

**Issue by OndroMih** [piranhacloud/piranha#2586]
**Describe the bug**
If browser points to / instead of to the jsp directly, the JSP is downloaded by the browser as a plain text file instead of rendering it as HTML.

To reproduce, create a simple WAR that contains index.jsp and add it to the welcome list in web.xml:

```
<welcome-file-list>
    <welcome-file>index.jsp</welcome-file>
  </welcome-file-list>
```

When loaded using the context root (e.g. http://localhost:8080/), the contents of the JSP file will be displayed. If loaded by the full path (e.g. http://localhost:8080/index.jsp), the HTML generated by the JSP fill be displayed as expected.

**Comment by mnriem** [comment]
It appears this fix has broken the com/sun/ts/tests/servlet/spec/welcomefiles/URLClient.java#partialfound2 Servlet TCK test

**Comment by mnriem** [comment]
@OndroMih Can you have a look?

**Comment by OndroMih** [comment]
How can I run the test locally?

**Comment by mnriem** [comment]
See https://github.com/piranhacloud/piranha/blob/current/CONTRIBUTING.md#run-the-external-tests-including-tcks, pass -Dsuspend if you want it to wait so you can attach a debugger

**Comment by OndroMih** [comment]
Thanks. I've fixed the test and didn't break any new test ;-) I had to refactor the code a bit so that it makes some more sense what it does. Now, the logic is simply:

For each welcome file in web.xml:
* if it's JSP and it's a static resource (the JSP file exists) -> return the JSP servlet
* if it's JSP but the JSP file doesn't exist -> ignore the entry
* if it's a static resource (not a JSP) -> return default servlet
* if it's something else (not a static resource, not a JSP) and a servlet exists for the URL -> return mapped servlet
* otherwise return null
