### ISSUE TITLE
Deprecate Piranha Nano and steer folks to Piranha Embedded

### ISSUE THREAD

**Issue by mnriem** [piranhacloud/piranha#2588]

**Comment by OndroMih** [comment]
What's the reason for this? I thought that Piranha Nano is suitable for cloud functions (e.g. AWS lambda) because it doesn't support HTTP session, for example. Is it possible to tweak Piranha Embedded to strip it down to what is absolutely necessary for cloud functions?

**Comment by mnriem** [comment]
@OndroMih Simplification of the overall offerings. In reality if you look at Piranha Nano and Piranha Embedded the only place they are different is the processing pipeline. So the intent here is to show how folks can migrate their code from Nano to Embedded by using Embedded and customizing the processing pipeline.

**Comment by OndroMih** [comment]
In that case, I think it's better to rather migrate from Embedded to Nano, as this would follow the Piranha philosophy to make it possible to "strip away all these features until only the bare libraries remain". I think that the functionality of Piranha Embedded should be achieved by starting with Piranha Nano and building upon it. I'm afraid Piranha Embedded is already too much for AWS Lambdas and if we don't offer a smaller distribution, there would be no way to achieve the same thing as with Nano nowadays. Besides that, I think that Nano is much better name than Embedded ;-)

**Comment by mnriem** [comment]
Eventually I think I would like to even deprecate Piranha Embedded and just describe how you would use the core Piranha API / implementation (2 Jars really) and then have a PiranhaBuilder API. And then demonstrate how to use that to deliver the equivalents of what Piranha Nano and Piranha Embedded do at the moment?  Thoughts? @OndroMih @arjantijms @Thihup

**Comment by OndroMih** [comment]
Yes, I agree @mnriem. Having just one thing is always better and straightforward. I would call everything just Piranha or Piranha Cloud. I think that even Piranha Micro and Server can be distributed as a set of dependencies plus a maven plugin that builds everything together. But sometimes having a downloadable runtime like Piranha Micro and Piranha Server may more convenient than having to build them from a maven project so I'm not against keeping Micro and Server.

**Comment by mnriem** [comment]
@OndroMih That is indeed the vision ;) So I will now go ahead and deprecate Piranha Nano .... so we can start that process. Note that generally speaking I like to deprecate first. Then in the next cycle deliver what folks should migrate to. And then in the cycle thereafter remove the deprecated code it gives folks 2-3 months if they are tracking the current branch ;)
