### ISSUE TITLE
Add warning when Http port and Https port are the same

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#2620]
_Originally posted by @Thihup in https://github.com/piranhacloud/piranha/issues/2619#issuecomment-1167201518_

**Comment by Thihup** [comment]
Initially fix for Piranha Micro, but might be needed for Piranha Server too

**Comment by salmansharifov** [comment]
@Thihup  Can I take this issue?

**Comment by Thihup** [comment]
@salmansharifov Sure, go for it!

**Comment by mnriem** [comment]
@salmansharifov @Thihup I would prefer the runtime to warn and exit if the ports used are the same
