### ISSUE TITLE
Document default port numbers

### ISSUE THREAD

**Issue by ParadoxV5** [piranhacloud/piranha#2625]
The default port numbers should be documented in `--help` and ideally on [the webpage](https://javadoc.io/doc/cloud.piranha/project/latest/resources/micro.html) as well.

_Originally mentioned in https://github.com/piranhacloud/piranha/issues/2619#issuecomment-1169251779_

**Comment by salmansharifov** [comment]
@Thihup Can I get this issue?

**Comment by Thihup** [comment]
Sure, go for it

**Comment by salmansharifov** [comment]
@Thihup Where it should be added? Server, Micro?

**Comment by Thihup** [comment]
Right now we already provide the HTTP port information when the `--verbose` flag is set for both Piranha Micro and Server

Micro: https://github.com/piranhacloud/piranha/blob/current/micro/dist/src/main/java/cloud/piranha/micro/MicroPiranhaBuilder.java#L221-L222

Server: (https://github.com/piranhacloud/piranha/blob/current/server/dist/src/main/java/cloud/piranha/server/ServerPiranhaBuilder.java#L225-L226.

Where we should add is on the following documentation pages:
https://github.com/piranhacloud/piranha/blob/current/src/main/javadoc/resources/micro.html
https://github.com/piranhacloud/piranha/blob/current/src/main/javadoc/resources/server.html

Maybe we should set the verbose flag to true by default? I don't think it would be great to have the same information in both verbose and in the help output. @mnriem thoughts?

**Comment by mnriem** [comment]
I rather not run in verbose mode by default. Chatty behavior should be an opt-in. Especially in a cloud world where logging is centrally captured.
