### ISSUE TITLE
Publish /core-profile/guides/rest/

### ISSUE THREAD

**Issue by mnriem** [piranhacloud/piranha#2750]
As the guide is currently referring to SNAPSHOT versions it has not been formally announced. Once the 22.9.0 release goes out the door the following has to happen.

1. Set Piranha version to a released version
2. Add proper link to Maven Central
3. Tweet about the guide
4. Update ZIP file

**Comment by mnriem** [comment]
@Thihup @arjantijms Can you please validate the content? See https://piranha.cloud/core-profile/guides/rest/

**Comment by Thihup** [comment]
Hi @mnriem.
It worked, but I had to [include the failsafe plugin](https://github.com/Thihup/piranha-rest-template/blob/piranha-core-profile/pom.xml#L85-L97) to make it run the integrated test, as in the tutorial, the test name is "HelloWorldIT", and surefire does not run "*IT" tests.

**Comment by Thihup** [comment]
Not fully related, but the tutorial uses the new `piranha-maven-plugin` . Do you plan to deprecate `piranha-server-maven-plugin` and `piranha-micro-maven-plugin` and merge them into `piranha-maven-plugin`?

**Comment by mnriem** [comment]
OK noted and I'll make sure to address that. Yes the plan is indeed to merge them into the `piranha-maven-plugin`.
