### ISSUE TITLE
Update ea workflow to use Java 20 EA

### ISSUE THREAD

**Issue by mnriem** [piranhacloud/piranha#2828]

**Comment by Thihup** [comment]
As soon as Temurin releases a 20-ea build, we can close this issue.

**Comment by mnriem** [comment]
Yea I jumped a wee bit too early ;) Maybe we should just opt for the Oracle OpenJDK one here as it is not like we say this is a supported scenario. It is merely to see if any of our changes would impact an upcoming Java release. Thoughts?

**Comment by Thihup** [comment]
I guess I'll remove all the distributions except Oracle OpenJDK EA
