### ISSUE TITLE
Deprecate cloud.piranha.http.api.HttpServer in favor of command line argument

### ISSUE THREAD

**Issue by mnriem** [piranhacloud/piranha#2831]
To be able to ship the Virtual Threads support as part of our default offerings we need to deprecate  the `cloud.piranha.http.api.HttpServer` services mechanism and allow the HTTP server implementation to be passed in as a command line argument.

Doing this will make it possible to add the Virtual Threads support to the Piranha Core Profile which folks can then enable using the command line argument when they are using Java 19+

**Comment by mnriem** [comment]
@Thihup Maybe something you want to take on?

**Comment by Thihup** [comment]
@mnriem Do you mean to include a check if the command line has a value and if not use the ServiceLoader, and include a warning log that using ServiceLoader is deprecated?

**Comment by mnriem** [comment]
Yes on both. Smart thinking on favoring the command line above the ServiceLoader. And then the release after the upcoming one we can remove ServiceLoader mechanism and then ship the Virtual Thread module as part of the Piranha Core Profile.

**Comment by OndroMih** [comment]
How that would work in the end?
The DefaultHttpServer would be the default server, and the VirtualThreads server would be bundled in Core Profile, but not enabled? And then the user can enable the VirtualThreads server with a command line optoin, passing the class name?

Such as `--http-server=cloud.piranha.http.virtual.VirtualHttpServer`?

And if the user adds their own implementation, e.g. `my.HttpServer`, he/she would enable it by `--http-server=my.HttpServer`?

**Comment by mnriem** [comment]
Correct, although I would prefer `--http-server-class` as the command line argument ;)

**Comment by mnriem** [comment]
Completed by #3057
