### ISSUE TITLE
Investigate feasibility of using Java on CRaC

### ISSUE THREAD

**Issue by mnriem** [piranhacloud/piranha#2842]
References

1. https://www.azul.com/blog/superfast-application-startup-java-on-crac/
2. https://openjdk.org/projects/crac/
3. https://github.com/CRaC/docs

Examples

1. https://github.com/CRaC/docs#examples

JDK on CRaC

1. https://github.com/CRaC/openjdk-builds/releases

**Comment by mnriem** [comment]
@Thihup Maybe something for you?

**Comment by mnriem** [comment]
@OndroMih Maybe something you want to try out? The PR enabling CRaC for Piranha Servlet has just been merged.

**Comment by OndroMih** [comment]
Looks good, I'll give it a try if I have enough time. Maybe I'll be able to use it in my JakartaOne presentation to show how to start Jakarta EE even faster with Piranha: https://jakartaone.org/2022/

**Comment by mnriem** [comment]
See https://piranha.cloud/servlet/guides/crac/ for a step by step guide. Note this guide is not considered officially published as it still requires the SNAPSHOT builds.
