### ISSUE TITLE
Replace Thread.sleep with Awaitility library in tests

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#3001]
Currently, Sonar shows warnings about using Thread.sleep in the tests.
They suggest using the Awaitility library instead.
@mnriem What do you think? Should we try to replace it in the tests?

**Comment by mnriem** [comment]
If it only for the tests go for it!

**Comment by salmansharifov** [comment]
@Thihup Can I take this?

**Comment by Thihup** [comment]
> @Thihup Can I take this?

@salmansharifov Sure, go for it
