### ISSUE TITLE
Add prototype for Piranha Embedded underneath Spring Boot

### ISSUE THREAD

**Issue by mnriem** [piranhacloud/piranha#3143]

**Comment by mnriem** [comment]
@OndroMih @Thihup  FYI feel free to try it out ;)

**Comment by Thihup** [comment]
Oh man, this is awesome!
Already tried it with a private application and it worked great first try!
Thank you @mnriem!

When I tried to add this feature some time ago I couldn't find the which was the correct class to implement😄
