### ISSUE TITLE
Review how DefaultAnnotationManager processes annotations

### ISSUE THREAD

**Issue by mnriem** [piranhacloud/piranha#3335]
For background, see https://github.com/eclipse-ee4j/jaxb-ri/issues/1703

**Comment by Thihup** [comment]
From what I recall, we currently do an eager loading of all classes in the artifact. 
This can lead to the situations described in the "background", but it also makes a large application take a long time to startup.

As one of the main goals is not to introduce any more dependencies in the core module, I didn't look for any other way to solve it (one way would be using Jandex). 
However, as the new [Classfile API][1] is being developed, we might use it to parse the class files and only load them if they include some of the annotations we're looking for. 

They will include the Classfile API in JDK 21 as a private API but in the future, they plan to release it, so we would still only depend on the Java class library.

[1]: https://openjdk.org/jeps/8280389

**Comment by mnriem** [comment]
@Thihup Feel free to keep an eye on those developments and hopefully we can then make the default implementation adopt this API once it is available for public use :)

**Comment by Thihup** [comment]
While the API is not public, I used reflection to try it out to see if it would work - and it does!
https://github.com/Thihup/piranha/commit/84c242303e09343c01074ddee624abfd5be5ea3e

The test case mentioned [here](https://github.com/eclipse-ee4j/jaxb-ri/issues/1703#issuecomment-1478539618) is now supported by running the application with 
`JDK_JAVA_OPTIONS="-Dcloud.piranha.extension.annotationscan.experimental.classfile=true" mvn piranha:run` (JDK-21 ea)

**Comment by mnriem** [comment]
Would it be something we can create as a separate module or do you think that would be overkill?

**Comment by Thihup** [comment]
@mnriem I think having a separate implementation using the Classfile API would be reasonable. However, it makes its usage more complicated for example running Piranha through the Maven plugin.

**Comment by mnriem** [comment]
We can still ship it as part of the regular distribution, but this separates it from a code perspective and is an opt-in so we keep the default implementation clean?

**Comment by Thihup** [comment]
Do you mean changing the code in the distributions from

```java
context.add(AnnotationScanExtension.class);                 // Annotation scanning
``` 
to something like
```java
if (System.getProperty("cloud.piranha.extension.annotationscan.experimental.classfile") != null) {
    context.add(AnnotationScanClassFileExtension.class);   // Annotation scanning using the new Classfile API
} else {
    context.add(AnnotationScanExtension.class);  // Annotation scanning
}
```

**Comment by Thihup** [comment]
They will change the Classfile API a little bit before the release of JDK 21, so I'll keep track of the changes and after it has been stabilized, I'll provide a PR.

They plan to include the Classfile API as a preview API in JDK 22. https://bugs.openjdk.org/browse/JDK-8280389
