### ISSUE TITLE
Add DispatchManager API

### ISSUE THREAD

**Issue by manorrock** [piranhacloud/piranha#339]

**Comment by amihaiemil** [comment]
@manorrock If you could file more specific Issues, with proper Descriptions of what needs to be done, maybe I'd be able to fix some of them :D

**Comment by manorrock** [comment]
@amihaiemil TCK compliance is a good one if you are looking for something to do. See the tck directory.

**Comment by amihaiemil** [comment]
@manorrock Not sure what to do there, I've never worked with TCKs :(

**Comment by arjantijms** [comment]
@amihaiemil Working with the TCK is a BIIIIGGGG challenge. Essentially in this context it means running it against Piranha (see Github actions where @manorrock has set things up how do that). Then at some point it fails where it wants to use say the DispatchManager from this issue. Then read the spec, see what it wants/needs and implement it.

Slightly easier is running https://github.com/javaee-samples/javaee7-samples against Piranha, e.g. the "servlet" folder. It will pass a lot of tests, but not all. What doesn't pass is a candidate for implementation. It's not easy and a lot of trial and error.

**Comment by manorrock** [comment]
Closing this as won't fix as we need to more clearly define the scope of the work with regards to how the ServletRequestDispatcher API will tie into the core Piranha runtime. As this indeed a large scope of work I am closing this so we can go through the process of using smaller issue to tackle this work.
