### ISSUE TITLE
Update FreePortFinder when modular support is delivered

### ISSUE THREAD

**Issue by mnriem** [piranhacloud/piranha#3423]
See https://github.com/alexpanov/freeportfinder/pull/8

**Comment by Thihup** [comment]
@mnriem What do you think of including the FreePortFinder class in the Piranha repository?
The whole project is basically just this [class][FreePortFinder].

[FreePortFinder]: https://github.com/alexpanov/freeportfinder/blob/master/src/main/java/me/alexpanov/net/FreePortFinder.java

**Comment by Thihup** [comment]
Also, we could search for another test library that does the same thing

**Comment by mnriem** [comment]
@Thihup Yea, as you filed it so long ago (more than a year ago) it is probably the better course of action. Feel free to go for it!

**Comment by Thihup** [comment]
Who would have thought that the pull request would be merged 😂

**Comment by mnriem** [comment]
Sometimes folks gets swamped and forget about it. Now hopefully we'll get a release
