### ISSUE TITLE
Replace Shrinkwrap Resolver with JResolve

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#3431]
Piranha Micro uses the Shrinkwrap Resolver to download the dependencies. However, this library is not modular, so it required some workarounds to work. 
There is a new library call [JResolve][JResolve], that is modular and uses the latest Java features. Currently it is targeting Java 21. We can see if this library would be useful for us, and maybe wait for the new LTS release or ask to see if the library could be downgraded to Java 17.

[JResolve]: https://github.com/bowbahdoe/jresolve

**Comment by mnriem** [comment]
Please go ahead and try it out on a feature branch (feature-jresolve).

**Comment by Thihup** [comment]
JResolve still needs to implement a few features before it can be usable in our project

**Comment by mnriem** [comment]
@Thihup Can this branch be deleted?

**Comment by Thihup** [comment]
Sure
