### ISSUE TITLE
Support Spring Boot Autoconfiguration

### ISSUE THREAD

**Issue by gmuth** [piranhacloud/piranha#3556]
**spring-boot-starter-piranha-embedded should support Autoconfiguration**

Piranha Embedded with Spring Boot requires manual configuration of a ServletWebServerFactory Bean as well as a WebServerFactoryCustomizer Bean. Spring Boot starters usually provide [autoconfigured](https://docs.spring.io/spring-boot/docs/3.1.4/reference/html/features.html#features.developing-auto-configuration) defaults.

**Comment by mnriem** [comment]
@gmuth Can you take care of this?

**Comment by gmuth** [comment]
Unfortunately no.
