### ISSUE TITLE
Classifying license as BSD-3-Clause

### ISSUE THREAD

**Issue by hyandell** [piranhacloud/piranha#3735]
Hi Piranha folk,

Would you be agreeable to a PR to change the pom.xml ( https://github.com/piranhacloud/piranha/blob/current/pom.xml#L23 ) from stating the license is `Piranha License` to `BSD-3-Clause` (the SPDX id for your license text ( https://github.com/piranhacloud/piranha/blob/current/LICENSE ))?

**Comment by mnriem** [comment]
@hyandell Thank you for raising the issue
