### ISSUE TITLE
Consider using Mima instead of Shrinkwrap Resolver

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#3744]
When checking out the JResolve repository, I've found the following comment:

> Shrinkwrap OTOH moved to MIMA https://github.com/maveniverse/mima and new upcoming CLI is https://github.com/maveniverse/toolbox

(https://github.com/bowbahdoe/jresolve/issues/3)

**Comment by mnriem** [comment]
@Thihup Go for it!

**Comment by mnriem** [comment]
See #3795 for why this is being closed as won't fix
