### ISSUE TITLE
Resuable Composition of Features or Initialisation Units

### ISSUE THREAD

**Issue by jbee** [piranhacloud/piranha#462]
@arjantijms described the feature https://github.com/piranhacloud/piranha/blob/master/test/jersey/src/test/java/cloud/piranha/test/jersey/JerseyTest.java#L56 idea a bit to me and I can see some parallels to what I did with bundles and modules in silk https://github.com/jbee/silk/blob/master/src/test/se/jbee/inject/bind/TestBinderModule.java#L42-L50.

The benefits of the system I came up with is that it allows to compose units for initialisation while still allowing other units to remove individual choices from other compositions and potentially replace them without becoming unpredictable for the user.

I sketch out a little thing, maybe it is helpful in the design of the features.

```java
interface Bundle {
   void bootstrap(Bootstrapper);
}
interface Bootstrapper {
   install(Class<? extends Bundle>);
   uninstall(Class<? extends Bundle>);
   install(Class<? extends Initializer>);
}
```
This now lets us do composition:
```java
class DefaultWebApp implements Bundle {
  public  void bootstrap(Bootstrapper context) {
     context.install(DefaultSecurityBundle.class);
     context.install(DefaultAuthorizationBundle.class);
     //...
  }
}
class DefaultAuthorizationBundle implements Bundle {
  public  void bootstrap(Bootstrapper context) {
    context.install(AuthorizationPreInitializer.class);
    context.install(AuthenticationInitializer.class);
    //...
  }
}
```
Now to bootstrap the full app with defaults you maybe build something like:
```java
EmbeddedPiranha piranha = new EmbeddedPiranhaBuilder()
                .directoryResource("src/main/webapp")
                .bootstrap(DefaultWebApp.class)
                .build()
                .initialize()
                .start();
```
Which then has two steps: 
1. find the set of `Bundle` classes that was `install`ed but never `uninstall`ed
2. collect all `Initializer` classes installed by each bundle

With this information you can now compute all `Initializer` classes that are "wanted" (never got uninstalled) and create them and run their init code. 

This might not seem so much more advanced at first sight but it allows you to do this:
```java
CustomWebApp implements Bundle {
  public  void bootstrap(Bootstrapper context) {
     context.install(DefaultWebApp.class);
     context.uninstall(DefaultSecurityBundle.class);
     context.install(CustomSecurityBundle.class);
     //...
  }
}
EmbeddedPiranha piranha = new EmbeddedPiranhaBuilder()
                .directoryResource("src/main/webapp")
                .bootstrap(CustomWebApp.class)
                .build()
                .initialize()
                .start();
```
So a user can make use of ready made compositions but still has a way to throw out the parts not wanted and replace them with a substitute or just skip them entirely. 

Taking this further the user can also do:
```java
TestWebApp implements Bundle {
  public  void bootstrap(Bootstrapper context) {
    context.install(CustomWebApp);
    context.uninstall(CustomSecurityBundle.class);
    context.install(MockSecurityBundle.class);
    //...
  }
}
EmbeddedPiranha piranha = new EmbeddedPiranhaBuilder()
                .directoryResource("src/main/webapp")
                .bootstrap(TestWebApp.class)
                .build()
                .initialize()
                .start();
```
And so forth. You can always mix and pick.

**Comment by manorrock** [comment]
@jbee I hope I did justice to your write up. Thanks for the suggestion!

**Comment by jbee** [comment]
I see you merged composition and configuration (change) into one abstraction. Surely is personal taste but I'd separate those two methods of `WebApplicationExtension` into two interfaces which also comes at the benefit of allowing to make them functional interfaces so lambdas become possible. 

It is also a good idea to split them since composition `extend` works on static level (`.class references, bootstrapping creates instances with `extension.newInstance()`) while the `configure` part might want to pass instances that have been initialised to a certain state. This often is not the case and both can be combined into one class that works on level of static references but it is handy to have that possibility. 

Functionality-wise the way add/remove works now is not what I tried to suggested. Remove is "shallow", it does not remove its "children". Which means to predict the effective outcome the user would need know which extensions were involved and in which order they were added and removed and would need to "compute" a wild mix of resulting extensions from that in his mind. That is impossible for any non-trivial setup. Which is why remove should not be shallow. Removing a extension must be as if it never had been referenced anywhere so that you can erase it from your mental list of things that have an effect. The result of such a semantic is predictable for humans even in larger compositions as you just strike one thing and all its consequences from your list and add another one to it. There is no order any longer. It is a declarative set of extensions you can look at in any order which means you can look at each of them in isolation and still predict the actual effective outcome as long as you know it was added but not removed.

Compare with https://github.com/jbee/silk/blob/master/src/core/se/jbee/inject/bootstrap/Bootstrap.java#L197-L215 and https://github.com/jbee/silk/blob/master/src/core/se/jbee/inject/bootstrap/Bootstrap.java#L297-L305.
