### ISSUE TITLE
Automate Docker Hub release

### ISSUE THREAD

**Issue by manorrock** [piranhacloud/piranha#582]

**Comment by amihaiemil** [comment]
@manorrock @arjantijms may I suggest to use [Rultor](https://www.rultor.com/) for automating stuff? It can help in automating ``merge``, ``deploy`` and ``release`` commands. 

I use it in all my projects, most notably to automate the release to Maven Central. Here is an example: https://github.com/amihaiemil/docker-java-api/issues/295 -- rultor helped me automate all [there](https://maven.apache.org/repository/guide-central-repository-upload.html) steps.

I am not the owner of rultor, but I have contributed code to it, so I can vouch for it's trustworthyness. 
What's interesting about rultor is that it performs each and every command (build) inside its own dedicated Docker container.

**Comment by manorrock** [comment]
@amihaiemil I appreciate your suggestions, but for automation we have decided on using GitHub actions where possible
