### ISSUE TITLE
Add Structure Diagram

### ISSUE THREAD

**Issue by amihaiemil** [piranhacloud/piranha#593]
I take the opportunity to open such requests since the project is still young!

I would like to see a structural diagram of this project. A simple PNG file, showing which modules are used and how they are tied together, which modules can be extended or replaced (actually plugins) etc.

**Comment by arjantijms** [comment]
@amihaiemil Amazing, as I was just planning this! :) 

In fact, the structure diagram was part of a larger plan, but it has to start somewhere.

**Comment by manorrock** [comment]
As an overall structure diagram would create a very dense diagram we have decided to deliver diagrams as part of the package documentation (where relevant). E.g see issue #615 and issue #616 as an example.
