### ISSUE TITLE
How can I override the default port on Piranha Micro?

### ISSUE THREAD

**Issue by otaviojava** [piranhacloud/piranha#623]
I went in the documentation and I did not find one way to overwrite the default port, 8080.

Is there any command to overwrite the port?
E.g.:

`  java -jar piranha-micro.jar --war your_webapplication.war --port 8888`

Reference: 
https://github.com/piranhacloud/piranha/tree/master/micro

**Comment by manorrock** [comment]
Not at the moment, but now in the queue

**Comment by manorrock** [comment]
The --port parameter is now supported and will be part of the 20.4.0 release

**Comment by manorrock** [comment]
Note if you want to try it out before the next release, please clone the Git repository and execute:

```
mvn -DskipTests -DskipITs verify
```

You can find the piranha-micro-all.jar in the micro/target directory

**Comment by otaviojava** [comment]
Thank you @manorrock
 I'll happy to write a blog post about it.

**Comment by otaviojava** [comment]
@manorrock do you have any date to this release?

**Comment by manorrock** [comment]
Our intent is every 13th of the month
