### ISSUE TITLE
Remove DefaultWebApplicationServer from Piranha Micro

### ISSUE THREAD

**Issue by manorrock** [piranhacloud/piranha#712]

**Comment by Thihup** [comment]
It should use the Piranha Embedded instead?

**Comment by manorrock** [comment]
In Piranha Micro we only have one web application that is ever active at any given time. It does not make sense to have the additional layer in between. The HttpServer layer and Piranha Micro could easily communicate directly by means of the HttpServerProcessor API. This issue was filed to explore how we can remove that intermediate layer here. The WebApplicationServer API only needs to be used in Piranha Server. Note I hope we CAN reuse the HttpServerProcessor that would come out of this in Piranha Server.

**Comment by manorrock** [comment]
See https://javadoc.piranha.cloud/cloud/piranha/micro/package-summary.html for diagram ;)

**Comment by manorrock** [comment]
Closing this as a won't fix as it is a premature optimization without real data
