### ISSUE TITLE
Deploying a expanded WAR file is not working Piranha Server

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#734]
I tried to deploy a expanded war (test.war) in Piranha Server and it didn't work.
I detected that other folder is created (test), but its content is empty.

The log says: "No web.xml found!"

It is not copying over the files of the expanded war to the new folder and thus is not deploying it.

**Comment by manorrock** [comment]
What do you mean with expanded WAR?

**Comment by Thihup** [comment]
I mean a extracted war file

**Comment by manorrock** [comment]
Piranha Server needs a WAR file. Piranha Micro allows the use of a exploded directory.
