### ISSUE TITLE
Add a main configuration file for Piranha Server

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#744]
All major servers have a configuration file to define some properties.

I'm opening this issue to let us start thinking about how structure the configurations, the file format, and so on.

I'd like to point that the Open Liberty's _server.xml_ is pretty impressive. Unlike other servers I used, in my option the configuration can be both clear and concise.

The XML for server configuration files is a convetion. I don't know what would be a good file format, but I'd like to hear what you think about using the [TOML](https://github.com/toml-lang/toml)

**Comment by manorrock** [comment]
For the configuration of web application we use web.xml. 

For the configuration of the server itself we use command line parameters.
