### ISSUE TITLE
Add more mime types

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#760]
Currently, we have only two default mime types, for CSS and JS in the DefaultMimeTypeManager.
I wonder if we will add more mime types on demand or if we can add some of them right now.

Tomcat has a exclusive properties file to handle a lot of Mime types.
https://github.com/apache/tomcat/blob/master/java/org/apache/catalina/startup/MimeTypeMappings.properties

**Comment by manorrock** [comment]
The number of default mime-types is kept to a minimum on purpose as each mime-type added requires extra processing. I have filed an issue for the Piranha website where we can document how one can add a larger set of mime-types. See https://github.com/piranhacloud/website/issues/3
