### ISSUE TITLE
Include Jakarta Annotation jar in Piranha Server

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#771]
In the _piranha-cdi-openwebbeans_ the jakarta.annotation.api is defined as scope "runtime", but in _piranha-cdi-weld_, it is defined as scope "provided", making the jar not available in runtime.

We should include it in other pom, change the scope of the dependency in piranha-cdi-weld or not include the jar at all?

**Comment by manorrock** [comment]
It should be runtime scope in piranha-cdi-weld as well
