### ISSUE TITLE
Add Bean Validation support to Piranha Server

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#794]

**Comment by manorrock** [comment]
Piranha Server, just like Piranha Micro, should use the WebApplicationExtension support to deliver support for additional libraries / dependencies. So we won't be adding any dependencies directly to Piranha Server. In the end the default extension for Piranha Server will be very similar to what Tomcat/Jetty deliver. At the moment if you want to enable a different extension you need to include a META-INF/services/cloud.piranha.webapp.api.WebApplicationExtension file that has a single line for the extension you want to enable in your WAR

**Comment by manorrock** [comment]
@arjantijms would love to find out how well Piranha Micro is working for you.

**Comment by manorrock** [comment]
Can I go ahead and close this one?
