### ISSUE TITLE
WebProfile extension in Piranha Micro

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#798]
I'd like to know if the correct use of it is _MicroCore + WebProfile_ or _MicroCore + MicroServlet + WebProfile_.

Currently it is working with the last option. But then we arrive at another issue. If we want to use the ApacheWebProfile extension, it happens a clash of CDI providers, because both MicroServlet and ApacheWebProfile include its own.

If we use only _MicroCore + ApacheWebProfile_, the Arquillian connector is not included and the JavaEE7-Samples don't pass any test.

My suggestion would be to use _MicroCore + WebProfile_, and include the Arquillian connector and related in both WebProfile extensions, but I want to know better how to compose these extensions.

**Comment by arjantijms** [comment]
Hi, thanks for remarking it. The MicroCore and MicroServlet extensions are still very new, I just committed those last week. We indeed still have to figure out how to best compose them. So at the moment there's really no correct use yet.

**Comment by Thihup** [comment]
Alright! I just like to point out that while I was trying the JavaEE7-Samples, I saw that the jars from WEB-INF/lib aren't being added as resource and thus causing a lot of NoClassDefFoundError.

**Comment by manorrock** [comment]
Our short-term plan is the deliver four end-to-end extensions that a user can select to use. They are not intended to be used together as each of those will deliver everything needed for that particular use case. 

They are:

1. Core
2. Servlet
3. WebProfile
4. Apache WebProfile

So if you are looking to run say an EE web-profile application you would pick 3 or 4 and that is all you would need.

**Comment by arjantijms** [comment]
> Alright! I just like to point out that while I was trying the JavaEE7-Samples, I saw that the jars from WEB-INF/lib aren't being added as resource and thus causing a lot of NoClassDefFoundError.

Yes, I haven't reached that part yet ;) But it's on my list to implement pretty soon. Thanks for the reminder!
