### ISSUE TITLE
Jakarta JSON Processing and Jakarta JSON Binding

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#799]
The WebProfile don't include implementation of JSON-P and JSON-B specs.
I think it would be good create a module for these specs, because there is the Apache Johnzon and it should be included in the ApacheWebProfile, while including both Yasson (JSON-B) and the Glassfish (JSON-P) implementation in the WebProfile.

I'd like to know if I it is OK to create a module for these extensions or include it directly in the pom.xml of both extensions.

**Comment by manorrock** [comment]
We only need to create extension modules for those dependencies that need further integration. If a dependency does not need to anything specific it should be added to the end-to-end extension module as a dependency.
