### ISSUE TITLE
Remove temporary workaround in MicroPiranha

### ISSUE THREAD

**Issue by manorrock** [piranhacloud/piranha#827]
Remove the tmp code block

        while (true) { //tmp
            try {
                Thread.sleep(2000);
            } catch (InterruptedException ie) {
                Thread.currentThread().interrupt();
            }
        }

**Comment by manorrock** [comment]
@arjantijms Is this code block still required? If so, why?

**Comment by arjantijms** [comment]
I think it would be best to just try to remove it and then see what happens, for instance running the Jakarta EE TCK inspired samples against it.

**Comment by manorrock** [comment]
Do we have tests that execute Piranha Micro in our regular testbed? Or are they all external?
