### ISSUE TITLE
Investigate adding EJB / Jakarta Enterprise Beans support

### ISSUE THREAD

**Issue by arjantijms** [piranhacloud/piranha#828]
Not the easiest thing in the world, but required for at least Web Profile certification is EJB (lite) support.

There's various options to consider:

1. Build from scratch (continue with https://github.com/omnifaces/omniservices)
1. Re-use [OpenEJB](http://openejb.apache.org)
1. Extract [EJB support from GlassFish](https://github.com/eclipse-ee4j/glassfish/tree/master/appserver/ejb) into reusable component 
1. Adopt and extend the abandoned [EasyBeans](https://repo1.maven.org/maven2/org/ow2/easybeans/osgi/easybeans-modules-core/3.0.0-M1/) project

**Comment by Thihup** [comment]
Does EJB lite contains a lot of stuff that can't be implemented with CDI?

**Comment by arjantijms** [comment]
> Does EJB lite contains a lot of stuff that can't be implemented with CDI?

Yes, that would be the build from scratch option. We have started that effort a while ago with some separate goodies: https://github.com/omnifaces/omniservices

In a way that's the preferred option, as that's where we're seeing EJB move anyway in Jakarta EE 10 and afterwards. (The options above were roughly ordered by preference).

So for the build from scratch, it would essentially boil down to extending `omniservices` with anything that's still missing, and add an extension that when seeing the EJB annotations programmatically adds the corresponding `omniservices` ones instead.

**Comment by manorrock** [comment]
Or look at the Manorrock Flounder project, see https://github.com/manorrock/flounder which uses the actual annotations and tells CDI to process them. Merging the 2 projects is also a possibility. I am not opposed to seeing a sub module in the Piranha project for this effort. But it'll take time to get it to EJB lite.

**Comment by manorrock** [comment]
Closing this as won't fix for now as it is too early for this
