### ISSUE TITLE
Add --ssl for SSL support

### ISSUE THREAD

**Issue by manorrock** [piranhacloud/piranha#831]

**Comment by Thihup** [comment]
Is the scope of this issue to enable SSL in all HTTP servers available or only to the default implementation?

**Comment by manorrock** [comment]
Both ;)

**Comment by Thihup** [comment]
Should the server start two HTTP ports? Like 8080 for HTTP and 8443 for HTTPS?
If so, I think we need to add a new "--httpsPort" to enable configure the HTTPS port.

**Comment by manorrock** [comment]
Note we will only support one HTTP/HTTPS endpoint for simplicity sake
