### ISSUE TITLE
Cannot open URL connection to libraries within war 

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#839]
In Piranha Micro, if the war contains a library, we cannot access it's contents by using the GlobalArchiveStreamHandler.

Example: _new URL("shrinkwrap://some.jar/some/file.properties").openConnection()_ is returning null because the resource manager contains only one resource (the war) and it checks if the name is the same [1] (it's always false). So it returns null.

[1] https://github.com/piranhacloud/piranha/blob/master/resource/shrinkwrap/src/main/java/cloud/piranha/resource/shrinkwrap/ShrinkWrapResource.java#L166

**Comment by manorrock** [comment]
Feel free to explore a patch. As a reminder Piranha Micro uses 2 resource managers, one for classloader resources and the other for web resources.

**Comment by manorrock** [comment]
@Thihup Is this still an issue?
