### ISSUE TITLE
Fix SingleThread HTTP server tests

### ISSUE THREAD

**Issue by manorrock** [piranhacloud/piranha#854]

**Comment by manorrock** [comment]
And what I feared happened the tests failed because it thinks the port is still in use. Feel free to separate each test on a separate port if that makes it all pass. If you do please make sure each of the operation has a negative and positive test.

**Comment by Thihup** [comment]
Let's revert for now

**Comment by Thihup** [comment]
Not so related, but can you enable the build for PRs?

**Comment by manorrock** [comment]
> Not so related, but can you enable the build for PRs?

Done
