### ISSUE TITLE
Fix ServletBasicTest

### ISSUE THREAD

**Issue by manorrock** [piranhacloud/piranha#855]

**Comment by Thihup** [comment]
The build failed because the tests requires the Shrinkwrap need the dependencies to be available.
Should we change the build.yml to _mvn --no-transfer-progress -P test install_?

**Comment by manorrock** [comment]
I rather not change the build.yml as I do not want to hamper onboarding. So if needs be the entire test could be moved to the test directory where we run integration tests and then of course be renamed to ServletBasicIT
