### ISSUE TITLE
Migrate tests to JUnit 5

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#911]
Shall we migrate the tests to JUnit 5 or is there any show stopper?

**Comment by manorrock** [comment]
No show stopper in my mind, but what does JUnit 5 buy us that JUnit 4 does not?

**Comment by Thihup** [comment]
I don't have a good reason right now. I think JUnit 4 doesn't have support anymore, but I'm afraid that the Arquillian tests may break.
As soon as I get some time I'll search for more information about JUnit 5. I know they have support for lambdas or something.

**Comment by manorrock** [comment]
I agree with @arjantijms in principle, but we should not regress in testing because of changing over to JUnit 5. So see if you can get all the tests to pass and if so we'll be ready to merge it all in.

**Comment by Thihup** [comment]
It was a very straightforward process to migrate. However, the Arquillian tests (in our case, the ServletBasicIT test) aren't fully compatible with only the new JUnit 5. For now, we can use the Vintage engine, that exists to help the migration. As soon as the Arquillian team releases a version compatible with JUnit 5 we can change that test.
I'll open a PR shortly.

**Comment by arjantijms** [comment]
> As soon as the Arquillian team releases a version compatible with JUnit 5 we can change that test.

Probably we need to do that PR, as I don't think they'll do it by themselves. I'll ping them here again though: https://github.com/arquillian/arquillian-core/issues/137
