### ISSUE TITLE
Fix the TCK Sample getRequestDispatcherTest 

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#919]
Fix the getRequestDispatcherTest.
Turns out that we need a default servlet to handle the requests to files. That test requires that `request.getRequestDispatcher("/WEB-INF/web.xml")` doesn't return null.

_Originally posted by @Thihup in https://github.com/piranhacloud/piranha/issues/912#issuecomment-651514704_

**Comment by manorrock** [comment]
We do have a DefaultServlet in the webapp/impl. If the getRequestDispatcher call is not working we need to validate it is being used and if it is, why it is NOT streaming the output, or if it is not being used, why not.

**Comment by Thihup** [comment]
Sure! Some points I can tell right away:
1. The _defaultServlet_ in DefaultWebApplication is null currently.
2. The getRequestDispatcher doesn't check for the _defaultServlet_, only for the _servlets_, causing it not to be found and thus returning null.

**Comment by manorrock** [comment]
Feel free to come up with a proposal on how to fix it, which passes all our tests and an additional one to validate this fix.

**Comment by Thihup** [comment]
It is fixed now
