### ISSUE TITLE
Rename jndi directory to naming (introduces Piranha Naming)

### ISSUE THREAD

**Issue by manorrock** [piranhacloud/piranha#922]

**Comment by manorrock** [comment]
To align with the rest of our codebase, can you also rename the implementation package to cloud.piranha.naming.impl and the groupId to cloud.piranha.naming and artifactId to piranha-naming-impl?

**Comment by Thihup** [comment]
Do we have a piranha-naming-impl? I could only find the piranha-naming-memory
