### ISSUE TITLE
Fix MicroProfile JWT TCK pipeline

### ISSUE THREAD

**Issue by manorrock** [piranhacloud/piranha#932]

**Comment by Thihup** [comment]
The MicroProfile JWT requires REST to be available to the container. However, the Piranha Micro doesn't include it by default, so no endpoints are available and all tests fail. 
I think it's not the goal to include a REST provider on the micro-servlet extension. I don't know if we should use another extension to run the tests, like webprofile extension. If so, we need to rework that extension.

**Comment by manorrock** [comment]
Please implement a micro-profile extension as per #936 and then circle back to validate it fixes this issue
