### ISSUE TITLE
Add --extension to Piranha Micro

### ISSUE THREAD

**Issue by manorrock** [piranhacloud/piranha#945]

**Comment by manorrock** [comment]
The --extension mechanism should be the default way to add extensions to Piranha Micro. Note the --extension parameter can be repeated to add multiple extensions

**Comment by Thihup** [comment]
Do you think we should start using some library to handle the arguments? If so, do you have any preferences?

**Comment by manorrock** [comment]
If you think we need to use a library I have one requirement and that it is a self-contained one (aka no other dependencies than itself)

**Comment by manorrock** [comment]
Closing as won't fix for now as current behavior does work
