### ISSUE TITLE
Support piranha-callers.xml from archive

### ISSUE THREAD

**Issue by arjantijms** [piranhacloud/piranha#957]
The content of a piranha-callers.xml file can now be read from a property, but not from the actual file in an archive. This should be fixed. Proposed location is `WEB-INF/piranha-callers.xml`.

**Comment by Thihup** [comment]
If we create a file with this name, I think we will need to create another file to do the JNDI bindings. Maybe we can use one file merge both configurations or use multiple files?

**Comment by arjantijms** [comment]
@Thihup That's a fair point to consider. This file here is largely like Tomcat's global `tomcat-users.xml`. Tomcat has the JNDI bindings in `/META-INF/context.xml`. GlassFish however has many of these things in a single file `glassfish-web.xml`.

This too is one if those things that hasn't really been decided yet.
