### ISSUE TITLE
Piranha Embedded - redundant initialization

### ISSUE THREAD

**Issue by vsmid** [piranhacloud/piranha#974]
Hi, 

i was playing with Piranha embedded (20.7.0) and i stumbled upon a problem while trying your [example](https://piranha.cloud/embedded/). 

```
EmbeddedPiranha piranha = new EmbeddedPiranhaBuilder()
    .servlet("SnoopServlet", SnoopServlet.class.getName())
    .servletMapping("SnoopServlet", "/SnoopServlet")
    .build()
    .initialize()
    .start();
```

.initialize() step contains redundant calls to many methods already executed in .build() step, breaks on status check where it expects SETUP value. After build step, app is already in INITIALIZED status.

I would create PR but i am not sure what the desired behaviour is just by looking at Piranha api.  My guess would be that build and initialize steps are not balanced well in this case.

**Comment by manorrock** [comment]
Thank you for trying out the example ... unfortunately it did not get updated ... the `initialize` method call is no longer necessary as the `build` method call already takes care of it ..
